# Generated by Django 2.0.3 on 2018-03-18 00:47

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields
import tatu.models


class Migration(migrations.Migration):

    dependencies = [
        ('tatu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default/avatar.png', upload_to=tatu.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
