# Generated by Django 2.0.3 on 2018-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
