# Generated by Django 2.0.3 on 2018-03-18 19:30

from django.db import migrations
import imagekit.models.fields
import tatu.models


class Migration(migrations.Migration):

    dependencies = [
        ('tatu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default/avatar.png', upload_to=tatu.models.user_avatar_path),
        ),
    ]
