# Generated by Django 2.0.3 on 2018-03-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatu', '0004_auto_20180318_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favourites',
            field=models.IntegerField(default=0),
        ),
    ]
