# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatu', '0005_auto_20180318_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='favourites',
            new_name='likes',
        ),
    ]
