# Generated by Django 2.0.3 on 2018-03-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatu', '0007_auto_20180316_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userid',
        ),
    ]
